[tools]
bun = "1.3.0"

[settings]
env_file = ".env"

[tasks]
install = "bun install"
start = "bun run src/index.ts"
dev = "bun --watch src/index.ts"
test = "bun test"

[tasks."test:watch"]
run = "bun test --watch"

[tasks."test:coverage"]
run = "bun test --coverage"

[tasks.setup]
description = "依存関係をインストールし、環境ファイルを初期化"
run = ["bun install", "if [ ! -f .env ]; then cp .env.example .env; fi"]
